services:
  weather-api:
    image: api-api
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      - mongo-db
    networks:
      - weather_net

  mongo-db:
    image: mongo:7.0
    ports:
      - "27017:27017"
    networks:
      - weather_net

networks:
  weather_net:
    external: true
