name: Deploy Node/Mongo App to GCP VM

on:
  push:
    branches:
      - main

env:
  VM_IP: 35.241.140.46

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Déploiement sur VM
        run: |
          echo "${{ secrets.GCP_SSH_PRIVATE_KEY }}" > temp-ssh-key.pem
          chmod 600 temp-ssh-key.pem

          ssh -o StrictHostKeyChecking=no -i temp-ssh-key.pem ubuntu@$VM_IP << 'EOF'
            set -e

            echo "Vérification Docker..."
            if ! command -v docker &>/dev/null; then
              curl -fsSL https://get.docker.com | sh
              sudo usermod -aG docker ubuntu
              newgrp docker
            fi

            echo "Vérification docker-compose..."
            if ! command -v docker-compose &>/dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-\$(uname -s)-\$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            echo "Préparation et déploiement..."
            cd /home/ubuntu
            rm -rf API
            git clone https://github.com/YStudentGroup/ApiWheather.git API
            cd API

            echo "MONGO_URI=mongodb://mongo-db:27017" > .env

            docker compose down || true
            docker compose up -d --build
          EOF

          rm -f temp-ssh-key.pem

